language: node_js
cache:
  directories:
  - "$HOME/.npm"
node_js:
- '10'
install:
  - npm ci
before_install:
 - printf "@redhat-cloud-services:registry=https://registry.npmjs.org/\n//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
before_script:
  - npm run build
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
