language: java
jdk:
  - openjdk11
env:
  - NODE_VERSION="16"
cache:
  directories:
  - "$HOME/.npm"
script:
 - nvm install $NODE_VERSION
 - printf "@redhat-cloud-services:registry=https://registry.npmjs.org/\n//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
 - npm ci
 - npm run build
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
